site_name: WSO2 Siddhi
extra_css:
- stylesheets/extra.css
extra:
  logo: images/siddhi-logo-w.svg
  palette:
    primary: teal
    accent: teal
pages:
- Welcome to WSO2 Siddhi: index.md
- Documentation:
  - Quick Start Guide: documentation/siddhi-quckstart-4.0.md
  - Siddhi Query Guide: documentation/siddhi-4.0.md
- Extensions: extensions.md
- About:
  - License: about/license.md
- Api:
  - 4.0.0-M15-SNAPSHOT: api/4.0.0-M15-SNAPSHOT.md
  - 4.0.0-M16-SNAPSHOT: api/4.0.0-M16-SNAPSHOT.md
- API Docs:
  - 4.0.0-M21-SNAPSHOT: api/4.0.0-M21-SNAPSHOT.md
theme: material
