site_name: WSO2 Siddhi
extra_css:
- stylesheets/extra.css
extra:
  logo: images/siddhi-logo-w.svg
  palette:
    primary: teal
    accent: teal
pages:
- Welcome to WSO2 Siddhi: index.md
- Documentation:
  - Quick Start Guide: documentation/siddhi-quckstart-4.0.md
  - Siddhi Query Guide: documentation/siddhi-4.0.md
- Extensions: extensions.md
- License: license.md
- API Docs:
  - 4.0.0-M25-SNAPSHOT: api/4.0.0-M25-SNAPSHOT.md
  - 4.0.0-M37: api/4.0.0-M37.md
  - 4.0.0-M36: api/4.0.0-M36.md
  - 4.0.0-M35: api/4.0.0-M35.md
  - 4.0.0-M39: api/4.0.0-M39.md
  - 4.0.0-M38: api/4.0.0-M38.md
theme: material
