site_name: Siddhi Core Libraries
site_description: Siddhi Core Libraries
repo_name: Siddhi
repo_url: https://github.com/siddhi-io/siddhi/
edit_uri: https://github.com/siddhi-io/siddhi/blob/master/
copyright: Siddhi - Documentation
theme:
  name: material
  logo: images/siddhi-logo.svg
  favicon: images/favicon.ico
  palette:
    primary: teal
    accent: teal
extra_css:
- assets/stylesheets/extra.css
extra_javascript:
- assets/javascripts/extra.js
extra:
  social:
  - type: github
    link: https://github.com/siddhi-io/siddhi
  - type: medium
    link: https://medium.com/siddhi-io
  - type: twitter
    link: https://twitter.com/siddhi_io
  - type: linkedin
    link: https://www.linkedin.com/groups/13553064
google_analytics:
- UA-103065-28
- auto
markdown_extensions:
- markdown.extensions.admonition
pages:
- Introduction: index.md
- API Docs:
  - latest: api/latest.md
  - 5.1.21: api/5.1.21.md
  - 5.1.20: api/5.1.20.md
  - 5.1.19: api/5.1.19.md
  - 5.1.18: api/5.1.18.md
  - 5.1.17: api/5.1.17.md
  - 5.1.16: api/5.1.16.md
  - 5.1.15: api/5.1.15.md
  - 5.1.14: api/5.1.14.md
  - 5.1.13: api/5.1.13.md
  - 5.1.12: api/5.1.12.md
  - 5.1.11: api/5.1.11.md
  - 5.1.10: api/5.1.10.md
  - 5.1.9: api/5.1.9.md
  - 5.1.8: api/5.1.8.md
  - 5.1.7: api/5.1.7.md
  - 5.1.6: api/5.1.6.md
  - 5.1.5: api/5.1.5.md
  - 5.1.4: api/5.1.4.md
  - 5.1.3: api/5.1.3.md
  - 5.1.2: api/5.1.2.md
  - 5.1.1: api/5.1.1.md
  - 5.1.0: api/5.1.0.md
  - 5.0.2: api/5.0.2.md
  - 5.0.1: api/5.0.1.md
  - 5.0.0: api/5.0.0.md
  - 4.5.11: api/4.5.11.md
  - 4.5.10: api/4.5.10.md
  - 4.5.9: api/4.5.9.md
  - 4.5.0: api/4.5.0.md
  - 4.4.8: api/4.4.8.md
  - 4.4.0: api/4.4.0.md
  - 4.3.19: api/4.3.19.md
  - 4.3.0: api/4.3.0.md
  - 4.2.40: api/4.2.40.md
  - 4.2.20: api/4.2.20.md
  - 4.2.0: api/4.2.0.md
  - 4.1.64: api/4.1.64.md
  - 4.1.46: api/4.1.46.md
  - 4.1.7: api/4.1.7.md
  - 4.1.0: api/4.1.0.md
  - 4.0.9: api/4.0.9.md
  - 4.0.0: api/4.0.0.md
- License: license.md
