site_name: Siddhi
site_description: Stream Processing and Complex Event Processing Engine
site_author: WSO2
site_url: http://siddhi.io
extra_css:
- stylesheets/extra.css
repo_name: Siddhi
repo_url: https://github.com/wso2/siddhi
copyright: Copyright &copy; 2011 - 2018 WSO2
theme:
  name: material
  logo: images/siddhi-logo-w.svg
  favicon: images/favicon.ico
  palette:
    primary: teal
    accent: teal
extra:
  social:
  - type: github
    link: https://github.com/wso2/siddhi
  - type: linkedin
    link: https://www.linkedin.com/groups/13553064
google_analytics:
- UA-103065-28
- auto
markdown_extensions:
- admonition
- toc:
    permalink: true
- codehilite:
    guess_lang: false
pages:
- Welcome to Siddhi: index.md
- Features: features.md
- Quick Start Guide: documentation/siddhi-5.x/quckstart-5.x.md
- Documentation:
  - Siddhi 5.x:
    - Quick Start Guide: documentation/siddhi-5.x/quckstart-5.x.md
    - User Guide: documentation/siddhi-5.x/user-guide-5.x.md
    - Siddhi Query Guide: documentation/siddhi-5.x/query-guide-5.x.md
    - Siddhi Architecture: documentation/siddhi-5.x/architecture-5.x.md
  - Siddhi 4.x:
    - Quick Start Guide: documentation/siddhi-4.x/quckstart-4.x.md
    - User Guide: documentation/siddhi-4.x/user-guide-4.x.md
    - Siddhi Query Guide: documentation/siddhi-4.x/query-guide-4.x.md
    - Siddhi Architecture: documentation/siddhi-4.x/architecture-4.x.md
- Contribute: contribution.md
- Extensions: extensions.md
- API Docs:
  - 5.0.0-m11: api/5.0.0-m11.md
  - 5.0.0-m10: api/5.0.0-m10.md
  - 5.0.0-m9: api/5.0.0-m9.md
  - 5.0.0-m8: api/5.0.0-m8.md
  - 5.0.0-m7: api/5.0.0-m7.md
  - 5.0.0-m6: api/5.0.0-m6.md
  - 5.0.0-m5: api/5.0.0-m5.md
  - 5.0.0-m4: api/5.0.0-m4.md
  - 5.0.0-m3: api/5.0.0-m3.md
  - 5.0.0-m2: api/5.0.0-m2.md
  - 5.0.0-m1: api/5.0.0-m1.md
  - 4.4.8: api/4.4.8.md
  - 4.4.0: api/4.4.0.md
  - 4.3.19: api/4.3.19.md
  - 4.3.0: api/4.3.0.md
  - 4.2.40: api/4.2.40.md
  - 4.2.20: api/4.2.20.md
  - 4.2.0: api/4.2.0.md
  - 4.1.64: api/4.1.64.md
  - 4.1.46: api/4.1.46.md
  - 4.1.7: api/4.1.7.md
  - 4.1.0: api/4.1.0.md
  - 4.0.9: api/4.0.9.md
  - 4.0.0: api/4.0.0.md
  - latest: api/latest.md
- License: license.md
- Google Season of Code 2019: season-of-docs-2019.md
