site_name: WSO2 Siddhi
extra_css:
- stylesheets/extra.css
extra:
  logo: images/siddhi-logo-w.svg
  palette:
    primary: teal
    accent: teal
site_favicon: images/favicon.ico
google_analytics:
- UA-103065-28
- auto
pages:
- Welcome to WSO2 Siddhi: index.md
- Features: features.md
- Quick Start Guide: documentation/siddhi-quckstart-4.0.md
- Documentation:
  - User Guide: documentation/user-guide.md
  - Siddhi Query Guide: documentation/siddhi-4.0.md
- Extensions: extensions.md
- API Docs:
  - 4.0.0-M60: api/4.0.0-M60.md
  - 4.0.0-M61: api/4.0.0-M61.md
  - 4.0.0-M62: api/4.0.0-M62.md
  - 4.0.0-M69: api/4.0.0-M69.md
  - 4.0.0-M70: api/4.0.0-M70.md
  - 4.0.0-M71: api/4.0.0-M71.md
  - 4.0.0-M72: api/4.0.0-M72.md
  - 4.0.0-M73: api/4.0.0-M73.md
  - 4.0.0-M74: api/4.0.0-M74.md
  - 4.0.0-M75: api/4.0.0-M75.md
  - 4.0.0-M76: api/4.0.0-M76.md
  - 4.0.0-M77: api/4.0.0-M77.md
  - 4.0.0-M78: api/4.0.0-M78.md
  - 4.0.0-M79-SNAPSHOT: api/4.0.0-M79-SNAPSHOT.md
- License: license.md
theme: material
