site_name: Siddhi
site_description: Stream Processing and Complex Event Processing Engine
site_author: WSO2
site_url: https://wso2.github.io/siddhi
extra_css:
- stylesheets/extra.css
repo_name: Siddhi
repo_url: https://github.com/wso2/siddhi
copyright: Copyright &copy; 2011 - 2018 WSO2
theme:
  name: material
  logo: images/siddhi-logo-w.svg
  favicon: images/favicon.ico
  palette:
    primary: teal
    accent: teal
extra:
  social:
  - type: github
    link: https://github.com/wso2/siddhi
  - type: linkedin
    link: https://www.linkedin.com/groups/13553064
google_analytics:
- UA-103065-28
- auto
markdown_extensions:
- admonition
- toc(permalink=true)
- codehilite(guess_lang=false)
pages:
- Welcome to Siddhi: index.md
- Features: features.md
- Quick Start Guide: documentation/siddhi-quckstart-4.0.md
- Documentation:
  - User Guide: documentation/user-guide.md
  - Siddhi Query Guide: documentation/siddhi-4.0.md
  - Siddhi Architecture: documentation/siddhi-architecture.md
- Extensions: extensions.md
- API Docs:
  - 4.2.32: api/4.2.32.md
  - 4.2.31: api/4.2.31.md
  - 4.2.30: api/4.2.30.md
  - 4.2.29: api/4.2.29.md
  - 4.2.28: api/4.2.28.md
  - 4.2.27: api/4.2.27.md
  - 4.2.26: api/4.2.26.md
  - 4.2.25: api/4.2.25.md
  - 4.2.24: api/4.2.24.md
  - 4.2.23: api/4.2.23.md
  - 4.2.22: api/4.2.22.md
  - 4.2.21: api/4.2.21.md
  - 4.2.20: api/4.2.20.md
  - 4.2.19: api/4.2.19.md
  - 4.2.18: api/4.2.18.md
  - 4.2.17: api/4.2.17.md
  - 4.2.16: api/4.2.16.md
  - 4.2.15: api/4.2.15.md
  - 4.2.14: api/4.2.14.md
  - 4.2.13: api/4.2.13.md
  - 4.2.12: api/4.2.12.md
  - 4.2.11: api/4.2.11.md
  - 4.2.10: api/4.2.10.md
  - 4.2.9: api/4.2.9.md
  - 4.2.8: api/4.2.8.md
  - 4.2.7: api/4.2.7.md
  - 4.2.6: api/4.2.6.md
  - 4.2.5: api/4.2.5.md
  - 4.2.4: api/4.2.4.md
  - 4.2.3: api/4.2.3.md
  - 4.2.2: api/4.2.2.md
  - 4.2.1: api/4.2.1.md
  - 4.2.0: api/4.2.0.md
  - 4.1.64: api/4.1.64.md
  - 4.1.63: api/4.1.63.md
  - 4.1.62: api/4.1.62.md
  - 4.1.61: api/4.1.61.md
  - 4.1.60: api/4.1.60.md
  - 4.1.46: api/4.1.46.md
  - 4.1.7: api/4.1.7.md
  - 4.1.0: api/4.1.0.md
  - 4.0.9: api/4.0.9.md
  - 4.0.0: api/4.0.0.md
  - latest: api/latest.md
- License: license.md
