site_name: Siddhi
site_description: Stream Processing and Complex Event Processing Engine
site_author: WSO2
site_url: https://wso2.github.io/siddhi
extra_css:
- stylesheets/extra.css
repo_name: Siddhi
repo_url: https://github.com/wso2/siddhi
copyright: Copyright &copy; 2011 - 2018 WSO2
theme:
  name: material
  logo: images/siddhi-logo-w.svg
  favicon: images/favicon.ico
  palette:
    primary: teal
    accent: teal
extra:
  social:
  - type: github
    link: https://github.com/wso2/siddhi
  - type: linkedin
    link: https://www.linkedin.com/groups/13553064
google_analytics:
- UA-103065-28
- auto
markdown_extensions:
- admonition
- toc(permalink=true)
- codehilite(guess_lang=false)
pages:
- Welcome to Siddhi: index.md
- Features: features.md
- Quick Start Guide: documentation/siddhi-quckstart-4.0.md
- Documentation:
  - User Guide: documentation/user-guide.md
  - Siddhi Query Guide: documentation/siddhi-4.0.md
  - Siddhi Architecture: documentation/siddhi-architecture.md
- Extensions: extensions.md
- API Docs:
  - 4.1.54: api/4.1.54.md
  - 4.1.53: api/4.1.53.md
  - 4.1.52: api/4.1.52.md
  - 4.1.51: api/4.1.51.md
  - 4.1.50: api/4.1.50.md
  - 4.1.49: api/4.1.49.md
  - 4.1.48: api/4.1.48.md
  - 4.1.47: api/4.1.47.md
  - 4.1.46: api/4.1.46.md
  - 4.1.45: api/4.1.45.md
  - 4.1.44: api/4.1.44.md
  - 4.1.43: api/4.1.43.md
  - 4.1.42: api/4.1.42.md
  - 4.1.41: api/4.1.41.md
  - 4.1.40: api/4.1.40.md
  - 4.1.39: api/4.1.39.md
  - 4.1.38: api/4.1.38.md
  - 4.1.37: api/4.1.37.md
  - 4.1.36: api/4.1.36.md
  - 4.1.35: api/4.1.35.md
  - 4.1.34: api/4.1.34.md
  - 4.1.13: api/4.1.13.md
  - 4.1.7: api/4.1.7.md
  - 4.1.6: api/4.1.6.md
  - 4.1.5: api/4.1.5.md
  - 4.1.0: api/4.1.0.md
  - 4.0.9: api/4.0.9.md
  - 4.0.0: api/4.0.0.md
  - latest: api/latest.md
- License: license.md
